# Generated by Django 5.2.7 on 2025-10-24 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_phone_appointment_status'),
    ]

    operations = [
    ]
