# Generated by Django 5.2.7 on 2025-12-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_customer_email_appointment_customer_name_and_more'),
    ]

    operations = [
    ]
